name: Deploy

on:
  push:
    branches:
      - main
  schedule:
    # cron every week on monday
    - cron: "0 0 * * 1"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Set Dockerfile name
        if: matrix.image.name != 'latest'
        run: echo "DOCKERFILE_NAME=${{ matrix.image.name }}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Get date for tags
        run: echo "DATE_TAG=$(date -I)" >> "$GITHUB_ENV"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            khulnasoft/kengine_file_server_ce:${{ matrix.image.name }}
            khulnasoft/kengine_file_server_ce:${{ matrix.image.name }}-${{ env.DATE_TAG }} 
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: khulnasoft/kengine_file_server_ce
